services:
    adadgio_graph.neo4j_manager:
        class: Adadgio\GraphBundle\ORM\Neo4jManager
        arguments: [ "%adadgio_graph.connection%" ]

    adadgio_graph.entity_listener:
        class: Adadgio\GraphBundle\Component\Listener\EntityEventListener
        tags:
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
        arguments: [ "@adadgio_graph.neo4j_manager" ]
